### ISSUE TITLE
Group membership and group locking

### ISSUE THREAD

**Issue by mongolsamurai** [rlazarus/MUSS#145]
I would like to see a standard attribute for recording some sort of group membership, and a lock subclass that checks same.
I will want to modify group membership using events, so ideally these things should be intercompatible.

**Comment by rlazarus** [comment]
We talked about this a little on IRC but I'm pretty sure locks.In is all this needs. I think it makes sense to implement groups as simple Python collections, owned by whatever code is using them -- that is, Player P's membership in Group G should be managed by G, not P, so that the permissions all work out the right way around -- I shouldn't be able to add myself to a group. We could put it on the player and use attribute locks to make sure everything goes through SYSTEM, but it seems just as easy, and much cleaner, not to.
